### ISSUE TITLE
Serialising AST header

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#65]
Please could you explain to me the reason behind serializing the header. It still floating above my head.

**Comment by gabordemooij** [comment]
Citrine can 'compile' programs. By doing this you can gain extra performance. However, since Citrine is an interpreted language, compiling in this context means something different. It serializes the AST (abstract syntax tree) to disk to skip the lexing and parsing steps. However, serializing also takes time, so instead of serializing/deserializing, Citrine writes the actual bytes to disk, directly. This however is not really possible because C pointers can be fragmented, to accomplish this task Citrine therefore works closely with its CTR memory allocator to align the memory blocks. To reload the byte code in memory Citrine 're-swizzles' the pointers according to addressbook entries stored in the header. It seems this technique is called 'pointer-swizzling', when I  searched for more info on 'C-swizzling' I found out it has a different meaning as well, oops.. :) lol
