### ISSUE TITLE
Idea for Threading/concurrency API

### ISSUE THREAD

**Issue by LeoTindall** [gabordemooij/citrine#9]
Given the ability to easily pass around executable code, I would think a threading API would be relatively easy to implement (or, at least, to conceptualize; I don't know much about threading in C.)

For example:

```
myThread := Thread new.
myThread on: 'start:' do: { number |
    Pen write: number, write: "Doing work...", brk.
    me yield.
    Pen write: number, write: "Doing more work...", brk.
}
var myThread01 := myThread new.
var myThread02 := myThread new.
myThread01 start: 1.
myThread02 start: 2.
```

The other option, as I see it, is to have each Thread or inherited object spawn a new thread when the message start is past, in effect acting as a thread factory.

Thoughts?

**Comment by gabordemooij** [comment]
I have to think about this, so much possibilities, your suggestion looks promising though...

**Comment by adamkao** [comment]
I much prefer the event-driven model, as used in Node.js, to threads, which I feel are hard to understand (mutex locks. etc.).

**Comment by gabordemooij** [comment]
what do you think about async etc? could we facilitate that as a message, somewhat like 'catch'?

**Comment by adamkao** [comment]
There's a problem.

In a dynamically scoped language with concurrency/parallelism the behavior of your program depends on the behavior of the scheduler, which is generally not visible to the programmer. In fact, if the scheduler is nondeterministic, your program may be nondeterministic. Fun!

So why is Citrine dynamically scoped?

see also http://clojure.org/index

**Comment by gabordemooij** [comment]
Dynamic scoping was easier to implement and I want to find a reason to upgrade to lexical scoping. However dynamic scoping offers a lot of benefits, it solves a lot of problems in dynamic OOP languages regarding dependency injection, service location, globals and wiring.

I'm not afraid of concurrency in Citrine, we already solved a lot of issues that seemed ugly at first but turned out to be trivial. I see concurrency as a challenge but also as a possibility to explore how parallellism may work together with dynamic scoping rules. Non-determinism is not really an option though. Well see what happens, it's fun!
