### ISSUE TITLE
Unit tests run out of order

### ISSUE THREAD

**Issue by twiggler** [gabordemooij/citrine#90]
On Ubuntu 17.01 running in VirtualBox in a freshly cloned copy of master,
the unit tests run in an undefined order
See the attached log.
[test.log](https://github.com/gabordemooij/citrine/files/1798558/test.log)

**Comment by gabordemooij** [comment]
Hi there ! ; ) This is to be expected and not a problem.
Each unit test covers a specific topic, unit tests should not be related and therefore order is unimportant.

**Comment by twiggler** [comment]
While that is true in general, with the current test runner the unit tests are effectively dependent because it terminates on the first failing unit test 😃; therefore, order is important.

I will tweak this behavior in my own copy for now; for the long term, I will think about another test runner.

**Comment by gabordemooij** [comment]
I disagree, if one test fails, there is no need to run the other tests, the failing test should be dealt with.  Most test systems are not strict enough, causing software to be shipped with multiple tests failing, I have experienced this first hand. Also, I don't see how this relates to order in general. I mean, why is order important because a single test failure stops the chain?

Why do you think order is important? Because the failing test should be at the end or beginning? You could run a single test, just by adding a custom personal script (like my personal x.sh?). I really don't see the relation between the fact that a single test can stop the batch and the fact that you find order important, unless you somehow want to put the newest test first, but in that case a custom script is simpler and cleaner because no additional logic is needed in the batch runner. Can you enlighten me?

**Comment by twiggler** [comment]
> I disagree, if one test fails, there is no need to run the other tests, the failing test should be dealt with.

I agree that a failing test should be dealt with. However, from experience, I also believe that when fixing a bug, it is helpful to have as much information as possible. By stopping at the first failing unit test, you limit the amount of information you can extract from your tests.

> Why do you think order is important? Because the failing test should be at the end or beginning?

I don't favor any particular order, but I prefer that the information I get from the tests is repeatable and as independent as possible from the environment in which the tests are run. Apparently, the order in which the tests are run currently depends on the development environment, which in itself is not a problem (although it makes the test results more difficult to parse IMO since the test report generation is tied to the order in which the tests are run). However, combined with the fact that a failed test stops the batch, the information the tests provide are needlessly dependent on the environment in which they are run.

> You could run a single test, just by adding a custom personal script (like my personal x.sh?)

Agreed, as stated above I have tweaked the behavior in my copy of the test runner.

The original reason I created this issue was that the proposed changes to the test runner could benefit other potential contributors / maintainers of citrine.

**Comment by gabordemooij** [comment]
> I agree that a failing test should be dealt with. However, from experience, I also believe that when fixing a bug, it is helpful to have as much information as possible. By stopping at the first failing unit test, you limit the amount of information you can extract from your tests.

It seems our experiences differ here. I find it more difficult to go to an entire output log to trace back tests that have failed. I have difficulty piecing all the information together. So, whenever a test fails, I write a custom script to investigate the issue and use that to distill the required information. I guess this is a difference in style. Unfortunately at my previous job failing tests where being ignored because the test runner would continue. I guess my attitude has been shaped by this experience as well.

> The original reason I created this issue was that the proposed changes to the test runner could benefit other potential contributors / maintainers of citrine.

The test runner should be improved indeed. There are several issues with it. However I would like to keep it short and simple and avoid tool-chain dependencies. I guess we could implement a flag to indicate whether tests may continue after failure or not (and set it to 'NO' for merge requests). Another issue I have with the current test runner is that it relies on bash specific scripting, it would be better to adhere to a more standard shell to improve portability, maybe Korn Shell?

**Comment by twiggler** [comment]
> Another issue I have with the current test runner is that it relies on bash specific scripting, it would be better to adhere to a more standard shell to improve portability, maybe Korn Shell?

I don't know; are there examples of environments where the current bash script does not function?

> However I would like to keep it short and simple and avoid tool-chain dependencies.

Fair enough.
To test my own contributions, I will probably switch to a more sophisticated test runner; I am afraid the current one is a little bit too bare bones for my taste :stuck_out_tongue_winking_eye:.

I'll take it that you are principally opposed to changing the build system to cmake?
